# The "base_url" should point to the domain and/or 
# subfolder in which you Junbi is located.

base_url = "http://hyperserious.biz/Junbidev"

name = "Junbi Dev Version"
version = "1.0"
author = "Jan Oelze"
